# Simplified docker-compose.yml - Google + Weaviate

services:
  backend:
    build: .
    container_name: saas-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=34.131.25.230
      - DB_PORT=5432
      - DB_NAME=salesdokdb
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
      - PLAYWRIGHT_BROWSERS_PATH=/home/appuser/.cache/ms-playwright
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      - TMPDIR=/app/tmp
      # Weaviate configuration
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
    volumes:
      - transformers_cache:/app/cache
      - playwright_cache:/home/appuser/.cache/ms-playwright
      - upload_storage:/app/uploads
      - temp_storage:/app/tmp
    depends_on:
      - weaviate
    restart: unless-stopped
    networks:
      - saas-network

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=
      - CLUSTER_HOSTNAME=node1
      - GRPC_PORT=50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge

volumes:
  transformers_cache:
  playwright_cache:
  upload_storage:
  temp_storage:
  weaviate_data: