# Updated docker-compose.yml

services:
  backend:
    build: .
    container_name: saas-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=34.131.25.230
      - DB_PORT=5432
      - DB_NAME=salesdokdb
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - MEMCACHE_HOST=memcache
      - MEMCACHE_PORT=11211
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
      - PLAYWRIGHT_BROWSERS_PATH=/home/appuser/.cache/ms-playwright
      - GCS_EMBEDDINGS_BUCKET=${GCS_EMBEDDINGS_BUCKET}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/focus-standard-467913-k2-c5f17486ddf9.json
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      # Fix temp directory path
      - TMPDIR=/app/tmp
    volumes:
      - transformers_cache:/app/cache
      - playwright_cache:/home/appuser/.cache/ms-playwright
      # Add volumes for file uploads and temp storage
      - upload_storage:/app/uploads
      - temp_storage:/app/tmp
       # Mount GCS service account key file
      - ./focus-standard-467913-k2-c5f17486ddf9.json:/app/focus-standard-467913-k2-c5f17486ddf9.json:ro

    depends_on:
      - memcache
    restart: unless-stopped
    networks:
      - saas-network

  memcache:
    image: memcached:1.6-alpine
    container_name: saas-memcache
    expose:
      - "11211"
    command: memcached -m 256 -v
    restart: unless-stopped
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge

volumes:
  transformers_cache:
  playwright_cache:
  upload_storage:    # For uploaded files
  temp_storage:      # For temporary processing