# Simplified docker-compose.yml - Google + External Qdrant
services:
  backend:
    build: .
    container_name: saas-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=34.131.25.230
      - DB_PORT=5432
      - DB_NAME=salesdokdb
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
      - PLAYWRIGHT_BROWSERS_PATH=/home/appuser/.cache/ms-playwright
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      - TMPDIR=/app/tmp
      # External Qdrant configuration
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION=kb_chunks
    volumes:
      - transformers_cache:/app/cache
      - playwright_cache:/home/appuser/.cache/ms-playwright
      - upload_storage:/app/uploads
      - temp_storage:/app/tmp:rw
    user: "1000:1000"  # Use host user permissions
    restart: unless-stopped
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge

volumes:
  transformers_cache:
  playwright_cache:
  upload_storage:
  temp_storage:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs